version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: file-manager-db
    pull_policy: if_not_present
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-file_manager}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: file-manager-backend
    pull_policy: if_not_present
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-file_manager}
      - PORT=3010
      - NODE_ENV=development
    ports:
      - "3010:3010"
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: file-manager-frontend
    pull_policy: if_not_present
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data: